title: Blog
author: Min Hwangbo
email: mhwangbo11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! I created this pilot blot to share my inssights around management in educational organizations. I hope you enjoy it!

# social links
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
